### ISSUE TITLE
Chapter 02 - Application Layer

### ISSUE THREAD

**Issue by luke0408** [Poin-Book/2023.09-network#2]
## 세팅
- [x] 참여자 별 Task 작성
- [x] 작성 참여자(Assignees) 등록
- [x] 파일 세팅

## Task 분배
- [x] Item 01 - Principles of Network Applications : @One-HyeWon 
- [x] Item 02 - The Web and HTTP : @One-HyeWon 
- [x] Item 03 - Electronic Mail in the Internet : @ShimFFF 
- [x] Item 04 - DNS : @ShimFFF 
- [x] Appendix_A - 과제 풀이 : @luke0408
